apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-aks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-helloworld
  template:
    metadata:
      labels:
        app: springboot-helloworld
    spec:
      containers:
        - name: springboot-helloworld-container
          image: codingguru.azurecr.io/springboot-helloworld:latest
          ports:
            - containerPort: 8029
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: springboot-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8029
  type: LoadBalancer
